<a href="https://colab.research.google.com/github/NadaTarekk/Courses-Recommandion/blob/main/Courses_Recommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the dependencies

In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Data Collection and Pre-Processing

In [2]:
# loading the data from the csv file to apandas dataframe
courses_data = pd.read_csv('/content/Courses.csv')

In [3]:
# printing the first 5 rows of the dataframe
courses_data.head()

Unnamed: 0                                        instructors  \
0           0                                  ['Jose Portilla']   
1           1                                  ['Dr. Angela Yu']   
2           2                                    ['Colt Steele']   
3           3                                  ['Dr. Angela Yu']   
4           4  ['Academind by Maximilian Schwarzmüller', 'Max...   

                                        course_title  rating  \
0  The Complete Python Bootcamp From Zero to Hero...     4.6   
1         The Complete 2023 Web Development Bootcamp     4.7   
2                    The Web Developer Bootcamp 2023     4.7   
3  100 Days of Code: The Complete Python Pro Boot...     4.7   
4  React - The Complete Guide 2023 (incl. React R...     4.6   

        numOfstudents                                       descriptions  \
0  1,823,671 students  Learn Python like a Professional  Start from t...   
1  1,137,534 students  Become a Full-Stack Web Developer with just ON...   
2    890,730 students  10 Hours of React just added. Become a Develop...   
3  1,098,710 students  Master Python by building 100 projects in 100 ...   
4    807,714 students  Dive in and learn React.js from scratch! Learn...   

  languages           lastUpdated  \
0   English   Last updated 7/2023   
1   English  Last updated 11/2023   
2   English  Last updated 11/2023   
3   English  Last updated 11/2023   
4   English  Last updated 11/2023   

                                                link       level  \
0  https://www.udemy.com/course/complete-python-b...  All Levels   
1  https://www.udemy.com/course/the-complete-web-...  All Levels   
2  https://www.udemy.com/course/the-web-developer...  All Levels   
3     https://www.udemy.com/course/100-days-of-code/  All Levels   
4  https://www.udemy.com/course/react-the-complet...  All Levels   

                category       numOfratings  
0  Programming Languages  (487,458 ratings)  
1        Web Development  (340,840 ratings)  
2        Web Development  (266,901 ratings)  
3  Programming Languages  (254,397 ratings)  
4  Programming Languages  (200,267 ratings)

In [4]:
# number of rows and columns in the data frame

courses_data.shape

(320, 12)

In [5]:
# selecting the relevant features for recommendation

selected_features = ['course_title','descriptions','category']
print(selected_features)

['course_title', 'descriptions', 'category']


In [6]:
# replacing the null valuess with null string

for feature in selected_features:
  courses_data[feature] = courses_data[feature].fillna('')

In [7]:
# combining all the selected features

combined_features = courses_data['course_title']+' '+courses_data['descriptions']+' '+courses_data['category']

In [8]:
print(combined_features)

0      The Complete Python Bootcamp From Zero to Hero...
1      The Complete 2023 Web Development Bootcamp Bec...
2      The Web Developer Bootcamp 2023 10 Hours of Re...
3      100 Days of Code: The Complete Python Pro Boot...
4      React - The Complete Guide 2023 (incl. React R...
                             ...                        
315    Ultimate Rust Crash Course Rust Programming Fu...
316    Microfrontends with React: A Complete Develope...
317    Data Integration Fundamentals Learn how to use...
318    Complete guide to building an app with .Net Co...
319    Artificial Intelligence & Machine Learning for...
Length: 320, dtype: object


In [9]:
# converting the text data to feature vectors

vectorizer = TfidfVectorizer()

In [10]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [11]:
print(feature_vectors)

  (0, 615)	0.11157813032536336
  (0, 844)	0.10528820129106936
  (0, 469)	0.21060522591356606
  (0, 98)	0.18428677294878085
  (0, 770)	0.22026839136290827
  (0, 1227)	0.14276696649129322
  (0, 272)	0.27317134406176297
  (0, 1182)	0.21060522591356606
  (0, 69)	0.19566991919014787
  (0, 486)	0.2025608462627612
  (0, 81)	0.14431293738458287
  (0, 143)	0.18181677807002086
  (0, 1024)	0.2025608462627612
  (0, 838)	0.22026839136290827
  (0, 632)	0.21519482497951173
  (0, 623)	0.08259410321716769
  (0, 535)	0.10938891958180237
  (0, 512)	0.2323702724805889
  (0, 1102)	0.17351240744988985
  (0, 1228)	0.2064152502427813
  (0, 455)	0.24864845261044116
  (0, 172)	0.15090872603929
  (0, 862)	0.37969310124863875
  (0, 231)	0.10150945222488422
  (0, 1088)	0.2379995371597852
  :	:
  (318, 334)	0.06854522274489758
  (318, 1185)	0.08393537482311132
  (318, 81)	0.1219958176093508
  (318, 1024)	0.17123604094907383
  (318, 1102)	0.22001965030833234
  (318, 455)	0.10509823936530624
  (318, 231)	0.1716232632

Cosine Similarity

In [12]:
# getting the similarity scores using cosine similarity

similarity = cosine_similarity(feature_vectors)

In [13]:
print(similarity)

[[1.         0.06937824 0.05721854 ... 0.07094398 0.14998272 0.02644502]
 [0.06937824 1.         0.59967904 ... 0.02138868 0.14006314 0.02456831]
 [0.05721854 0.59967904 1.         ... 0.01356227 0.1549244  0.02427219]
 ...
 [0.07094398 0.02138868 0.01356227 ... 1.         0.05503489 0.0834945 ]
 [0.14998272 0.14006314 0.1549244  ... 0.05503489 1.         0.01274954]
 [0.02644502 0.02456831 0.02427219 ... 0.0834945  0.01274954 1.        ]]


In [14]:
print(similarity.shape)

(320, 320)


Getting the movie name from the user

In [15]:
# getting the movie name from the user

course_name = input(' Enter your favourite course name : ')

 Enter your favourite course name : 


In [16]:
# finding the index of the course with title

index_of_the_movie = courses_data[courses_data.course_title == course_name].index.tolist()[0]
index_of_the_movie

IndexError: list index out of range

In [ ]:
# getting a list of similar courses

similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

In [ ]:
len(similarity_score)

In [ ]:
# sorting the courses based on their similarity score

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_movies)

In [17]:
# print the name of similar courses based on the index

print('Courses suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = courses_data[courses_data.index==index]['course_title'].values[0]
  if (i<11):
    print(i, '.',title_from_index)
    i+=1

Courses suggested for you : 



NameError: name 'sorted_similar_movies' is not defined

Movie Recommendation Sytem

In [20]:
course_name = input(' Enter your favourite course name : ')

index_of_the_movie = courses_data[courses_data.course_title == course_name].index.tolist()[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)

print('Movies suggested for you : \n')

i = 2

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = courses_data[courses_data.index==index]['course_title'].values[0]
  if (i<10):
    print(i, '.',title_from_index)
    i+=1

 Enter your favourite course name : Artificial Intelligence & Machine Learning for Business
Movies suggested for you : 

2 . Artificial Intelligence & Machine Learning for Business
3 . Complete Machine Learning & Data Science Bootcamp 2023
4 . Machine Learning for Absolute Beginners - Level 1
5 . Tensorflow 2.0: Deep Learning and Artificial Intelligence
6 . Artificial Intelligence A-Z 2023: Build 5 AI (incl. ChatGPT)
7 . Data Science and Machine Learning Bootcamp with R
8 . The Complete Machine Learning Course with Python
9 . Introduction to Machine Learning for Data Science
