<a href="https://colab.research.google.com/github/NadaTarekk/PQC-Toy-Kyber/blob/main/Courses_Recommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the dependencies

In [3]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Data Collection and Pre-Processing

In [64]:
# loading the data from the csv file to apandas dataframe
courses_data = pd.read_csv('/content/Courses.csv')

In [65]:
# printing the first 5 rows of the dataframe
courses_data.head()

Unnamed: 0                                        instructors  \
0           0                                  ['Jose Portilla']   
1           1                                  ['Dr. Angela Yu']   
2           2                                    ['Colt Steele']   
3           3                                  ['Dr. Angela Yu']   
4           4  ['Academind by Maximilian Schwarzmüller', 'Max...   

                                        course_title  rating  \
0  The Complete Python Bootcamp From Zero to Hero...     4.6   
1         The Complete 2023 Web Development Bootcamp     4.7   
2                    The Web Developer Bootcamp 2023     4.7   
3  100 Days of Code: The Complete Python Pro Boot...     4.7   
4  React - The Complete Guide 2023 (incl. React R...     4.6   

        numOfstudents                                       descriptions  \
0  1,823,671 students  Learn Python like a Professional  Start from t...   
1  1,137,534 students  Become a Full-Stack Web Developer with just ON...   
2    890,730 students  10 Hours of React just added. Become a Develop...   
3  1,098,710 students  Master Python by building 100 projects in 100 ...   
4    807,714 students  Dive in and learn React.js from scratch! Learn...   

  languages           lastUpdated  \
0   English   Last updated 7/2023   
1   English  Last updated 11/2023   
2   English  Last updated 11/2023   
3   English  Last updated 11/2023   
4   English  Last updated 11/2023   

                                                link       level  \
0  https://www.udemy.com/course/complete-python-b...  All Levels   
1  https://www.udemy.com/course/the-complete-web-...  All Levels   
2  https://www.udemy.com/course/the-web-developer...  All Levels   
3     https://www.udemy.com/course/100-days-of-code/  All Levels   
4  https://www.udemy.com/course/react-the-complet...  All Levels   

                category       numOfratings  
0  Programming Languages  (487,458 ratings)  
1        Web Development  (340,840 ratings)  
2        Web Development  (266,901 ratings)  
3  Programming Languages  (254,397 ratings)  
4  Programming Languages  (200,267 ratings)

In [67]:
# number of rows and columns in the data frame

courses_data.shape

(320, 12)

In [68]:
# selecting the relevant features for recommendation

selected_features = ['course_title','descriptions','category']
print(selected_features)

['course_title', 'descriptions', 'category']


In [69]:
# replacing the null valuess with null string

for feature in selected_features:
  courses_data[feature] = courses_data[feature].fillna('')

In [70]:
# combining all the selected features

combined_features = courses_data['course_title']+' '+courses_data['descriptions']+' '+courses_data['category']

In [71]:
print(combined_features)

0      The Complete Python Bootcamp From Zero to Hero...
1      The Complete 2023 Web Development Bootcamp Bec...
2      The Web Developer Bootcamp 2023 10 Hours of Re...
3      100 Days of Code: The Complete Python Pro Boot...
4      React - The Complete Guide 2023 (incl. React R...
                             ...                        
315    Ultimate Rust Crash Course Rust Programming Fu...
316    Microfrontends with React: A Complete Develope...
317    Data Integration Fundamentals Learn how to use...
318    Complete guide to building an app with .Net Co...
319    Artificial Intelligence & Machine Learning for...
Length: 320, dtype: object


In [72]:
# converting the text data to feature vectors

vectorizer = TfidfVectorizer()

In [73]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [74]:
print(feature_vectors)

  (0, 615)	0.11157813032536336
  (0, 844)	0.10528820129106936
  (0, 469)	0.21060522591356606
  (0, 98)	0.18428677294878085
  (0, 770)	0.22026839136290827
  (0, 1227)	0.14276696649129322
  (0, 272)	0.27317134406176297
  (0, 1182)	0.21060522591356606
  (0, 69)	0.19566991919014787
  (0, 486)	0.2025608462627612
  (0, 81)	0.14431293738458287
  (0, 143)	0.18181677807002086
  (0, 1024)	0.2025608462627612
  (0, 838)	0.22026839136290827
  (0, 632)	0.21519482497951173
  (0, 623)	0.08259410321716769
  (0, 535)	0.10938891958180237
  (0, 512)	0.2323702724805889
  (0, 1102)	0.17351240744988985
  (0, 1228)	0.2064152502427813
  (0, 455)	0.24864845261044116
  (0, 172)	0.15090872603929
  (0, 862)	0.37969310124863875
  (0, 231)	0.10150945222488422
  (0, 1088)	0.2379995371597852
  :	:
  (318, 334)	0.06854522274489758
  (318, 1185)	0.08393537482311132
  (318, 81)	0.1219958176093508
  (318, 1024)	0.17123604094907383
  (318, 1102)	0.22001965030833234
  (318, 455)	0.10509823936530624
  (318, 231)	0.1716232632

Cosine Similarity

In [75]:
# getting the similarity scores using cosine similarity

similarity = cosine_similarity(feature_vectors)

In [76]:
print(similarity)

[[1.         0.06937824 0.05721854 ... 0.07094398 0.14998272 0.02644502]
 [0.06937824 1.         0.59967904 ... 0.02138868 0.14006314 0.02456831]
 [0.05721854 0.59967904 1.         ... 0.01356227 0.1549244  0.02427219]
 ...
 [0.07094398 0.02138868 0.01356227 ... 1.         0.05503489 0.0834945 ]
 [0.14998272 0.14006314 0.1549244  ... 0.05503489 1.         0.01274954]
 [0.02644502 0.02456831 0.02427219 ... 0.0834945  0.01274954 1.        ]]


In [77]:
print(similarity.shape)

(320, 320)


Getting the movie name from the user

In [78]:
# getting the movie name from the user

course_name = input(' Enter your favourite course name : ')

 Enter your favourite course name : Java 17 Masterclass: Start Coding in 2023


In [80]:
# finding the index of the course with title

index_of_the_movie = courses_data[courses_data.course_title == course_name].index.tolist()[0]
index_of_the_movie

7

In [81]:
# getting a list of similar courses

similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.23278693885085067), (1, 0.024618525562576234), (2, 0.024321800310143242), (3, 0.06127296866644732), (4, 0.06415703824173792), (5, 0.019184462059873456), (6, 0.035353593821795544), (7, 1.0000000000000002), (8, 0.0565096574599969), (9, 0.007669620074199825), (10, 0.052011193135413), (11, 0.08243246332038576), (12, 0.15759336457261572), (13, 0.02779796600751539), (14, 0.020048410542290167), (15, 0.09630081130929827), (16, 0.026674991451471376), (17, 0.0228458369272778), (18, 0.020756561640518017), (19, 0.018666991992675578), (20, 0.04488264266133592), (21, 0.0329949676409229), (22, 0.025560679582105093), (23, 0.0762302482776451), (24, 0.12423787773016381), (25, 0.19209073790626938), (26, 0.05414308039502293), (27, 0.09494674595820438), (28, 0.0), (29, 0.012534873419146407), (30, 0.0), (31, 0.09972571239701288), (32, 0.056412266464088284), (33, 0.013145716710159194), (34, 0.08354521262581764), (35, 0.008692323754557143), (36, 0.0), (37, 0.03995182403031077), (38, 0.04796546203907943

In [82]:
len(similarity_score)

320

In [83]:
# sorting the courses based on their similarity score

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_movies)

[(7, 1.0000000000000002), (138, 0.33115551059411213), (49, 0.31434143994745317), (135, 0.2938672477784605), (260, 0.2927002165042204), (195, 0.2667291654590683), (80, 0.25678342182033814), (149, 0.2485442198025443), (189, 0.23957085372683257), (221, 0.23572594657029952), (96, 0.23549201778937684), (0, 0.23278693885085067), (61, 0.23191610261478157), (282, 0.201877598497648), (308, 0.19985312155136084), (25, 0.19209073790626938), (264, 0.18726684507835467), (185, 0.18561496715192044), (307, 0.18339943820674784), (276, 0.17234349508818467), (84, 0.1595277690022893), (251, 0.1589792063787607), (12, 0.15759336457261572), (209, 0.15300947589439487), (216, 0.14749498572073788), (249, 0.1454071218396351), (64, 0.14457015572227847), (237, 0.14229720091005077), (177, 0.1390770604991466), (56, 0.13715660140701336), (268, 0.1345855175634204), (73, 0.1332744850015047), (151, 0.13169700543019222), (236, 0.12743141136848), (107, 0.12678731681450883), (255, 0.1266505227577757), (134, 0.12485951106381

In [85]:
# print the name of similar courses based on the index

print('Courses suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = courses_data[courses_data.index==index]['course_title'].values[0]
  if (i<11):
    print(i, '.',title_from_index)
    i+=1

Courses suggested for you : 

1 . Java 17 Masterclass: Start Coding in 2023
2 . Java Programming: Complete Beginner to Advanced
3 . Java Programming for Complete Beginners
4 . Learn JAVA Programming - Beginner to Master
5 . Complete Python Programming Masterclass Beginner to Advanced
6 . Python for Data Structures, Algorithms, and Interviews!
7 . The Complete Java Certification Course
8 . Core Java Made Easy (Covers the latest Java 17)
9 . Programming with Python : HandsOn Introduction for Beginners
10 . Modern Java - Learn Java 8 Functional Features By coding it


Movie Recommendation Sytem

In [91]:
course_name = input(' Enter your favourite course name : ')

index_of_the_movie = courses_data[courses_data.course_title == course_name].index.tolist()[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = courses_data[courses_data.index==index]['course_title'].values[0]
  if (i<11):
    print(i, '.',title_from_index)
    i+=1

 Enter your favourite course name : Complete C# Unity Game Developer 2D
Movies suggested for you : 

1 . Complete C# Unity Game Developer 2D
2 . Complete C# Unity Game Developer 3D
3 . The Ultimate Guide to Game Development with Unity (Official)
4 . RPG Core Combat Creator: Learn Intermediate Unity C# Coding
5 . Unreal Engine Blueprint Game Developer
6 . Unreal Engine 5: The Complete Beginner's Course
7 . Unreal Engine 5 C++ Developer: Learn C++ & Make Video Games
8 . Blender Character Creator for Video Games Design
9 . Complete C# Masterclass
10 . Unreal Engine 4: How to Develop Your First Two Games
