<a href="https://colab.research.google.com/github/NadaTarekk/Courses-Recommandion/blob/main/Courses_Recommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the dependencies

In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Data Collection and Pre-Processing

In [2]:
# loading the data from the csv file to apandas dataframe
courses_data = pd.read_csv('/content/Courses.csv')

In [3]:
# printing the first 5 rows of the dataframe
courses_data.head()

Unnamed: 0                                        instructors  \
0           0                                  ['Jose Portilla']   
1           1                                  ['Dr. Angela Yu']   
2           2                                    ['Colt Steele']   
3           3                                  ['Dr. Angela Yu']   
4           4  ['Academind by Maximilian Schwarzmüller', 'Max...   

                                        course_title  rating  \
0  The Complete Python Bootcamp From Zero to Hero...     4.6   
1         The Complete 2023 Web Development Bootcamp     4.7   
2                    The Web Developer Bootcamp 2023     4.7   
3  100 Days of Code: The Complete Python Pro Boot...     4.7   
4  React - The Complete Guide 2023 (incl. React R...     4.6   

        numOfstudents                                       descriptions  \
0  1,823,671 students  Learn Python like a Professional  Start from t...   
1  1,137,534 students  Become a Full-Stack Web Developer with just ON...   
2    890,730 students  10 Hours of React just added. Become a Develop...   
3  1,098,710 students  Master Python by building 100 projects in 100 ...   
4    807,714 students  Dive in and learn React.js from scratch! Learn...   

  languages           lastUpdated  \
0   English   Last updated 7/2023   
1   English  Last updated 11/2023   
2   English  Last updated 11/2023   
3   English  Last updated 11/2023   
4   English  Last updated 11/2023   

                                                link       level  \
0  https://www.udemy.com/course/complete-python-b...  All Levels   
1  https://www.udemy.com/course/the-complete-web-...  All Levels   
2  https://www.udemy.com/course/the-web-developer...  All Levels   
3     https://www.udemy.com/course/100-days-of-code/  All Levels   
4  https://www.udemy.com/course/react-the-complet...  All Levels   

                category       numOfratings  
0  Programming Languages  (487,458 ratings)  
1        Web Development  (340,840 ratings)  
2        Web Development  (266,901 ratings)  
3  Programming Languages  (254,397 ratings)  
4  Programming Languages  (200,267 ratings)

In [4]:
# number of rows and columns in the data frame

courses_data.shape

(320, 12)

In [5]:
# selecting the relevant features for recommendation

selected_features = ['course_title','descriptions','category']
print(selected_features)

['course_title', 'descriptions', 'category']


In [6]:
# replacing the null valuess with null string

for feature in selected_features:
  courses_data[feature] = courses_data[feature].fillna('')

In [7]:
# combining all the selected features

combined_features = courses_data['course_title']+' '+courses_data['descriptions']+' '+courses_data['category']

In [8]:
print(combined_features)

0      The Complete Python Bootcamp From Zero to Hero...
1      The Complete 2023 Web Development Bootcamp Bec...
2      The Web Developer Bootcamp 2023 10 Hours of Re...
3      100 Days of Code: The Complete Python Pro Boot...
4      React - The Complete Guide 2023 (incl. React R...
                             ...                        
315    Ultimate Rust Crash Course Rust Programming Fu...
316    Microfrontends with React: A Complete Develope...
317    Data Integration Fundamentals Learn how to use...
318    Complete guide to building an app with .Net Co...
319    Artificial Intelligence & Machine Learning for...
Length: 320, dtype: object


In [9]:
# converting the text data to feature vectors

vectorizer = TfidfVectorizer()

In [10]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [11]:
print(feature_vectors)

  (0, 615)	0.11157813032536336
  (0, 844)	0.10528820129106936
  (0, 469)	0.21060522591356606
  (0, 98)	0.18428677294878085
  (0, 770)	0.22026839136290827
  (0, 1227)	0.14276696649129322
  (0, 272)	0.27317134406176297
  (0, 1182)	0.21060522591356606
  (0, 69)	0.19566991919014787
  (0, 486)	0.2025608462627612
  (0, 81)	0.14431293738458287
  (0, 143)	0.18181677807002086
  (0, 1024)	0.2025608462627612
  (0, 838)	0.22026839136290827
  (0, 632)	0.21519482497951173
  (0, 623)	0.08259410321716769
  (0, 535)	0.10938891958180237
  (0, 512)	0.2323702724805889
  (0, 1102)	0.17351240744988985
  (0, 1228)	0.2064152502427813
  (0, 455)	0.24864845261044116
  (0, 172)	0.15090872603929
  (0, 862)	0.37969310124863875
  (0, 231)	0.10150945222488422
  (0, 1088)	0.2379995371597852
  :	:
  (318, 334)	0.06854522274489758
  (318, 1185)	0.08393537482311132
  (318, 81)	0.1219958176093508
  (318, 1024)	0.17123604094907383
  (318, 1102)	0.22001965030833234
  (318, 455)	0.10509823936530624
  (318, 231)	0.1716232632

Cosine Similarity

In [12]:
# getting the similarity scores using cosine similarity

similarity = cosine_similarity(feature_vectors)

In [13]:
print(similarity)

[[1.         0.06937824 0.05721854 ... 0.07094398 0.14998272 0.02644502]
 [0.06937824 1.         0.59967904 ... 0.02138868 0.14006314 0.02456831]
 [0.05721854 0.59967904 1.         ... 0.01356227 0.1549244  0.02427219]
 ...
 [0.07094398 0.02138868 0.01356227 ... 1.         0.05503489 0.0834945 ]
 [0.14998272 0.14006314 0.1549244  ... 0.05503489 1.         0.01274954]
 [0.02644502 0.02456831 0.02427219 ... 0.0834945  0.01274954 1.        ]]


In [14]:
print(similarity.shape)

(320, 320)


Getting the movie name from the user

In [15]:
# getting the course name from the user

course_name = input(' Enter your favourite course name : ')

 Enter your favourite course name : The Complete Machine Learning Course with Python


In [17]:
# finding the index of the course with title

index_of_the_course= courses_data[courses_data.course_title == course_name].index.tolist()[0]
index_of_the_course

312

In [18]:
# getting a list of similar courses

similarity_score = list(enumerate(similarity[index_of_the_course]))
print(similarity_score)

[(0, 0.11890891072065889), (1, 0.046048266141302176), (2, 0.07961729748454317), (3, 0.153503886747495), (4, 0.0270294701082329), (5, 0.06051169206006948), (6, 0.0860595156395465), (7, 0.0), (8, 0.42451406198720265), (9, 0.4233792172261476), (10, 0.3428132669480586), (11, 0.05791159199075033), (12, 0.09463373380727468), (13, 0.013260807455679296), (14, 0.0880033799724734), (15, 0.1867793830488312), (16, 0.046885565781208574), (17, 0.052328385437558744), (18, 0.05080418714678874), (19, 0.0), (20, 0.15687158583794003), (21, 0.05756220177205023), (22, 0.02700804293539908), (23, 0.010732552809084315), (24, 0.04640136684152853), (25, 0.0), (26, 0.20709041301759365), (27, 0.2258587373188109), (28, 0.037452737428392106), (29, 0.04697626043091033), (30, 0.10529322640434166), (31, 0.414610394736968), (32, 0.13434524299220288), (33, 0.0520973278588583), (34, 0.1842912756808154), (35, 0.09992042574012636), (36, 0.02558714664400431), (37, 0.008835258041622523), (38, 0.05472439712104191), (39, 0.055

In [ ]:
len(similarity_score)

In [19]:
# sorting the courses based on their similarity score

sorted_similar_courses = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_courses)

[(312, 1.0000000000000002), (112, 0.49367482646320404), (164, 0.48556022527725556), (132, 0.45800581934725876), (8, 0.42451406198720265), (9, 0.4233792172261476), (31, 0.414610394736968), (67, 0.4080335684189152), (301, 0.3725194705356546), (161, 0.36710439466014927), (10, 0.3428132669480586), (41, 0.3350162902904742), (319, 0.32102669212826557), (215, 0.30931164044345943), (235, 0.3062528479971871), (55, 0.29996863112012484), (145, 0.2599142880598945), (126, 0.2470229783516565), (94, 0.24359488880588492), (246, 0.24292502763883336), (27, 0.2258587373188109), (77, 0.22232695366154467), (48, 0.22210804521348707), (306, 0.21920061273565125), (227, 0.21388397869701448), (26, 0.20709041301759365), (295, 0.20466123362602168), (272, 0.1983774376861039), (243, 0.19544197182048206), (15, 0.1867793830488312), (219, 0.18438429677650917), (34, 0.1842912756808154), (107, 0.18370998173553638), (231, 0.17755972249215538), (111, 0.1704429403485775), (90, 0.1659822179039982), (260, 0.16334628557060366

In [21]:
# print the name of similar courses based on the index

print('Courses suggested for you : \n')

i = 1

for course in sorted_similar_courses:
  index = course[0]
  title_from_index = courses_data[courses_data.index==index]['course_title'].values[0]
  if (i<11):
    print(i, '.',title_from_index,' score is: ',course[1])
    i+=1

Courses suggested for you : 

1 . The Complete Machine Learning Course with Python  score is:  1.0000000000000002
2 . Complete Machine Learning & Data Science Bootcamp 2023  score is:  0.49367482646320404
3 . Python for Machine Learning & Data Science Masterclass  score is:  0.48556022527725556
4 . Data Science and Machine Learning Bootcamp with R  score is:  0.45800581934725876
5 . Machine Learning A-Z™: AI, Python & R + ChatGPT Bonus [2023]  score is:  0.42451406198720265
6 . Python for Data Science and Machine Learning Bootcamp  score is:  0.4233792172261476
7 . Complete Python Developer in 2023: Zero to Mastery  score is:  0.414610394736968
8 . Machine Learning, Data Science and Generative AI with Python  score is:  0.4080335684189152
9 . Machine Learning for Absolute Beginners - Level 1  score is:  0.3725194705356546
10 . Introduction to Machine Learning for Data Science  score is:  0.36710439466014927


Movie Recommendation Sytem

In [23]:
course_name = input(' Enter your favourite course name : ')

index_of_the_course = courses_data[courses_data.course_title == course_name].index.tolist()[0]

similarity_score = list(enumerate(similarity[index_of_the_course]))

sorted_similar_courses = sorted(similarity_score, key = lambda x:x[1], reverse = True)

print('Courses suggested for you : \n')

i = 2

for course in sorted_similar_courses:
  index = course[0]
  title_from_index = courses_data[courses_data.index==index]['course_title'].values[0]
  if (i<10):
    print(i, '.',title_from_index,' score is: ',course[1])
    i+=1

 Enter your favourite course name : Artificial Intelligence & Machine Learning for Business
Courses suggested for you : 

2 . Artificial Intelligence & Machine Learning for Business  score is:  1.0000000000000002
3 . Complete Machine Learning & Data Science Bootcamp 2023  score is:  0.4979828118082842
4 . Machine Learning for Absolute Beginners - Level 1  score is:  0.45416352528362874
5 . Tensorflow 2.0: Deep Learning and Artificial Intelligence  score is:  0.3987914200556463
6 . Artificial Intelligence A-Z 2023: Build 5 AI (incl. ChatGPT)  score is:  0.3920346208467642
7 . Data Science and Machine Learning Bootcamp with R  score is:  0.35906733375469474
8 . The Complete Machine Learning Course with Python  score is:  0.32102669212826557
9 . Introduction to Machine Learning for Data Science  score is:  0.31849853580740073
